providers = ["python"]

[phases.setup]
nixPkgs = ["ffmpeg", "libopus"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"

[start]
cmd = "python -u bots/api_server.py"

